apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: bookstore
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgrespass"
  POSTGRES_DB: "bookstore"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-app-credentials
  namespace: bookstore
type: Opaque
stringData:
  DB_USER: "bookstore_app"
  DB_PASSWORD: "bookstore_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-db
  namespace: bookstore
type: Opaque
stringData:
  DATABASE_URL: "postgresql://bookstore_app:bookstore_pass@postgresql.bookstore.svc.cluster.local:5432/bookstore?options=-c%20search_path%3Dcatalog"
  DB_SCHEMA: "catalog"
---
apiVersion: v1
kind: Secret
metadata:
  name: cart-service-db
  namespace: bookstore
type: Opaque
stringData:
  DATABASE_URL: "postgresql://bookstore_app:bookstore_pass@postgresql.bookstore.svc.cluster.local:5432/bookstore?options=-c%20search_path%3Dcart"
  DB_SCHEMA: "cart"
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-db
  namespace: bookstore
type: Opaque
stringData:
  DATABASE_URL: "postgresql://bookstore_app:bookstore_pass@postgresql.bookstore.svc.cluster.local:5432/bookstore?options=-c%20search_path%3Dinventory"
  DB_SCHEMA: "inventory"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-db
  namespace: bookstore
type: Opaque
stringData:
  DATABASE_URL: "postgresql://bookstore_app:bookstore_pass@postgresql.bookstore.svc.cluster.local:5432/bookstore?options=-c%20search_path%3Dorder"
  DB_SCHEMA: "order"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-db
  namespace: bookstore
type: Opaque
stringData:
  DATABASE_URL: "postgresql://bookstore_app:bookstore_pass@postgresql.bookstore.svc.cluster.local:5432/bookstore?options=-c%20search_path%3Dpayment"
  DB_SCHEMA: "payment"
---
apiVersion: v1
kind: Secret
metadata:
  name: recommendation-service-db
  namespace: bookstore
type: Opaque
stringData:
  DATABASE_URL: "postgresql://bookstore_app:bookstore_pass@postgresql.bookstore.svc.cluster.local:5432/bookstore?options=-c%20search_path%3Drecommendation"
  DB_SCHEMA: "recommendation"
